name: CI_AppColorNote
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.15.1
        - name: Install
          run: npm install
        - name: Test
          env:
            BROWSERSTACK_USER: ${{ secrets.BS_USER}}
            BROWSERSTACK_KEY: ${{ secrets.BS_KEY}}
          run: 
            npm test wdio.bs.conf.js --spec test/specs/appColorNote/*.spec.js

