name: GitHub Actions
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.15.1
        - name: Install
          run: npm install
        - name: Test
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: npm test wdio.conf.js --spec test/specs/appColorNote/addNote.spec.js
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
